### PR TITLE
Change seconds args to float

### LINKED ISSUE #14: 0 sent instead of decimal when setting increase/decrease prewait
When you are sending a decimal value, ie 0.5/.5 seconds, for a Prewait time (qlab: Increase Prewait or qlab: Decrease Prewait) the OSC message that is sent is "/cue/selected/preWait/+ 0"

The decimal value is ignored and a 0 value is sent causing the command to fail.

If i send 1.5 then it sends "/cue/selected/preWait/+ 1"

Decrease Prewait does the same thing.

### PR DESCRIPTION
**Pull request by istnv**
This is the same update I did for qlab-advance.
Should close #14.

### CODE REVIEW

**Comment by krocheck** [comment]
Has there been any testing against this?

**Comment by istnv** [comment]
It works for me on 4 QLab shows on 2 different macbooks. One has companion on the same mac, the other is remote from companion on Linux.

**Comment by krocheck** [comment]
@istnv why did you opt to close this PR?

**Comment by istnv** [comment]
Didn't intend to. Fat fingers. I did want to check that HELP.md language was correct.

**Comment by krocheck** [comment]
Did you need to update that language or is this good to go?

**Comment by istnv** [comment]
It's ready. HELP.md doesn't specify whole seconds on those actions.

**Pull request merged**
